import ChampionStats from "@/components/ChampionStats";
import Footer, { socialLinks } from "@/components/Footer";
import BookingForm from "@/components/BookingForm";
import { useState } from "react";
import { products } from "@/data/products";
import ProductCard from "@/components/ProductCard";
import { ArrowDownRight, ArrowRight, Clock3, Dumbbell, Instagram, MapPin, Menu, MoveUpRight, ShieldCheck, Sparkles, Trophy, X } from "lucide-react";

const img = { hero: "/WhatsApp%20Image%202026-09-20%20at%2000.09.14.jpeg", gym: "/salle-de-musculation.png", products: "/manus-storage/marius-products_a83edb69.jpg" };

const milestones = [
  ["2023—24", "Les premiers podiums", "Deux premières éditions des championnats nationaux. Marius apprend les critères, affine sa ligne et s’impose déjà comme un athlète à suivre."],
  ["OCT. 2025", "La consécration nationale", "À Porto-Novo, il remporte la catégorie reine Men's Body 1 (+80 kg), puis le Super podium et le titre de Meilleur athlète de l'année au Bénin."],
  ["AOÛT 2026", "Le sommet mondial", "À Yaoundé, il représente le Bénin au Championnat du Monde WFF et décroche le titre mondial dans la catégorie Super Body."],
];
function go(id: string) { document.getElementById(id)?.scrollIntoView({ behavior: "smooth" }); }
function Label({ children, light = false }: { children: React.ReactNode; light?: boolean }) { return <div className={`mb-5 flex items-center gap-3 font-mono text-[10px] font-bold uppercase tracking-[0.3em] ${light ? "text-[#d7c8be]" : "text-[#9b2d35]"}`}><span className="h-px w-8 bg-[#9b2d35]" />{children}</div>; }
function Brand() { return <a href="#top" className="flex items-center gap-3"><span className="relative flex h-10 w-10 items-center justify-center bg-red-600 text-white shadow-[4px_4px_0_#f0e8dd]"><span className="font-display text-xl italic">P</span><span className="absolute -right-1 -top-1 h-2 w-2 bg-[#f4c660]" /></span><span><span className="block font-display text-lg uppercase tracking-[0.08em] text-[#f4eee5]">Patati</span><span className="block font-mono text-[9px] uppercase tracking-[0.32em] text-[#9f958d]">Abadahoué</span></span></a>; }

export default function Home() {
  const [open, setOpen] = useState(false);
  const nav = [["Le champion", "champion"], ["Le palmarès", "palmares"], ["La salle", "salle"], ["La boutique", "boutique"]];
  const contact = () => go("reservation");
  return <div id="top" className="min-h-screen overflow-hidden bg-[#111113] text-[#f4eee5]">
    <header className="fixed inset-x-0 top-0 z-50 border-b border-white/10 bg-[#111113]/85 backdrop-blur-xl"><div className="container flex h-[74px] items-center justify-between"><Brand /><nav className="hidden gap-8 lg:flex">{nav.map(([label, id]) => <button key={id} onClick={() => go(id)} className="font-mono text-[10px] uppercase tracking-[0.2em] text-[#aba29a] hover:text-[#f4eee5]">{label}</button>)}</nav><button onClick={contact} className="hidden items-center gap-2 border border-[#9b2d35] px-4 py-2.5 font-mono text-[10px] font-bold uppercase tracking-[0.18em] hover:bg-[#9b2d35] sm:flex">Rejoindre le mouvement <ArrowRight className="h-3.5 w-3.5" /></button><button onClick={() => setOpen(!open)} className="flex h-10 w-10 items-center justify-center border border-white/10 lg:hidden" aria-label="Menu">{open ? <X /> : <Menu />}</button></div>{open && <div className="border-t border-white/10 bg-[#111113] p-5 lg:hidden">{nav.map(([label, id]) => <button key={id} onClick={() => { go(id); setOpen(false); }} className="flex w-full justify-between py-3 font-mono text-xs uppercase tracking-[0.18em] text-[#c9bfb7]">{label}<ArrowDownRight className="text-[#9b2d35]" /></button>)}</div>}</header>
    <main>
      <section className="relative flex min-h-[760px] items-end overflow-hidden border-b border-white/10 pt-[74px] lg:min-h-[840px]"><div className="absolute inset-0 bg-[radial-gradient(circle_at_72%_45%,rgba(155,45,53,0.32),transparent_32%),linear-gradient(90deg,#111113_0%,rgba(17,17,19,0.76)_38%,rgba(17,17,19,0.28)_100%)]" /><div className="absolute inset-y-0 right-0 w-full bg-cover bg-center opacity-80 mix-blend-screen lg:w-[67%]" style={{ backgroundImage: `url(${img.hero})` }} /><div className="hero-noise absolute inset-0 opacity-40" /><div className="container relative z-10 grid w-full gap-12 pb-16 pt-24 lg:grid-cols-[1fr_360px] lg:pb-24"><div className="max-w-3xl"><div className="mb-8 flex flex-wrap items-center gap-4"><span className="inline-flex items-center gap-2 bg-[#f4eee5] px-3 py-2 font-mono text-[10px] font-bold uppercase tracking-[0.2em] text-[#111113]"><span className="h-2 w-2 rounded-full bg-[#9b2d35]" />Champion du monde WFF 2026</span><span className="font-mono text-[10px] uppercase tracking-[0.2em] text-[#c4b7ad]">Bénin · Super Body</span></div><h1 className="font-display text-[clamp(5rem,13vw,11rem)] uppercase leading-[0.78] tracking-[-0.035em]">Patati<br /><span className="pl-[11vw] text-[#9b2d35]">Patata</span></h1><p className="mt-10 max-w-xl border-l-2 border-[#9b2d35] pl-5 text-base leading-7 text-[#d6cbc2] sm:text-lg">Marius Bignon Abadahoué. Une discipline de fer, une vision claire et le drapeau béninois au sommet du bodybuilding mondial.</p><div className="mt-10 flex flex-wrap gap-4"><button onClick={() => go("champion")} className="flex items-center gap-3 bg-[#9b2d35] px-5 py-4 font-mono text-[10px] font-bold uppercase tracking-[0.2em] hover:bg-[#bc3943]">Découvrir son histoire <ArrowDownRight /></button><a href="/catalogue" className="flex items-center gap-3 px-2 py-4 font-mono text-[10px] font-bold uppercase tracking-[0.2em] hover:text-[#f4c660]">Voir le catalogue <MoveUpRight className="text-[#9b2d35]" /></a></div></div><div className="hidden self-end border-l-2 border-[#f4c660] bg-[#111113]/90 p-6 shadow-xl backdrop-blur-sm lg:block"><p className="font-mono text-[11px] font-medium uppercase tracking-[0.18em] text-[#eee5dc]">Dernière consécration</p><p className="mt-4 font-display text-5xl uppercase leading-[0.95] text-white">Yaoundé<br /><span className="text-[#f4c660]">2026</span></p><div className="mt-5 h-px w-16 bg-[#f4c660]" /><p className="mt-5 max-w-[260px] text-base leading-7 text-[#f4eee5]">Le titre mondial WFF rejoint une trajectoire déjà marquée par 9 médailles et 4 trophées.</p></div></div></section>
      <section id="champion" className="scroll-mt-24 bg-[#f4eee5] py-24 text-[#171619] lg:py-32"><div className="container"><div className="grid gap-16 lg:grid-cols-[0.8fr_1.2fr] lg:gap-24"><div><Label>Le champion</Label><h2 className="font-display text-[clamp(3.8rem,8vw,7rem)] uppercase leading-[0.83]">La force<br /><span className="text-[#9b2d35]">avec du sens.</span></h2><ChampionStats /></div><div className="max-w-2xl lg:pt-12"><p className="font-display text-3xl uppercase leading-[1.05] sm:text-4xl">“Je lui dois ce trophée. C’est lui qui m’a formé pour que je devienne son dauphin.”</p><div className="mt-12 grid gap-10 border-t border-[#171619]/15 pt-10 sm:grid-cols-2"><div><p className="font-mono text-[10px] font-bold uppercase tracking-[0.2em] text-[#9b2d35]">Le duo complice</p><p className="mt-4 text-sm leading-7 text-[#5e5650]">Marius attribue une immense part de ses performances à son mentor et préparateur physique, <strong>Romain Zannou</strong>, champion national du Bénin en 2024.</p></div><div><p className="font-mono text-[10px] font-bold uppercase tracking-[0.2em] text-[#9b2d35]">La méthode</p><p className="mt-4 text-sm leading-7 text-[#5e5650]">Nutrition stricte, gestion du sommeil et entraînements intensifs : la victoire est une somme de choix quotidiens.</p></div></div><button onClick={contact} className="mt-10 flex items-center gap-3 border-b-2 border-[#9b2d35] pb-2 font-mono text-[10px] font-bold uppercase tracking-[0.18em]">Travailler avec l’équipe <ArrowRight className="text-[#9b2d35]" /></button></div></div></div></section>
      <section id="palmares" className="scroll-mt-24 bg-[#171619] py-24 lg:py-32"><div className="container"><div className="flex flex-col justify-between gap-8 border-b border-white/10 pb-10 sm:flex-row sm:items-end"><div><Label light>Palmarès</Label><h2 className="font-display text-[clamp(3.8rem,8vw,7rem)] uppercase leading-[0.8]">Une trajectoire<br /><span className="text-[#9b2d35]">en or.</span></h2></div><p className="font-mono text-[10px] uppercase leading-5 tracking-[0.16em] text-[#8e8580]">Début de carrière officielle<br />2023 / Porto-Novo → Yaoundé</p></div><div className="mt-12">{milestones.map(([year, title, copy], i) => <div key={year} className="grid gap-6 border-b border-white/10 py-8 sm:grid-cols-[130px_70px_1fr]"><p className="font-mono text-[11px] font-bold tracking-[0.2em] text-[#bbaea4]">{year}</p><p className="font-display text-3xl text-[#9b2d35]">0{i + 1}</p><div className="max-w-xl"><h3 className="font-display text-3xl uppercase text-[#f4eee5] sm:text-4xl">{title}</h3><p className="mt-4 text-sm leading-7 text-[#8f8782]">{copy}</p></div></div>)}</div></div></section>
      <section id="salle" className="scroll-mt-24 bg-[#f4eee5] py-24 text-[#171619] lg:py-32">
        <div className="container">
          <div className="grid gap-12 lg:grid-cols-[1fr_1fr] lg:items-center">
            <div className="relative min-h-[430px] overflow-hidden bg-[#222] sm:min-h-[580px]">
              <img src={img.gym} alt="Espace d’entraînement et de musculation" className="absolute inset-0 h-full w-full object-cover opacity-85 grayscale-[0.35]" />
              <div className="absolute inset-0 bg-gradient-to-t from-[#171619]/90 via-transparent to-[#171619]/10" />
              <div className="absolute left-5 top-5 flex items-center gap-3 bg-[#f4eee5] px-3 py-2 font-mono text-[9px] font-bold uppercase tracking-[0.18em]"><MapPin className="h-4 w-4 text-[#9b2d35]" />Cococodji · Bénin</div>
              <div className="absolute bottom-8 left-6 right-6"><p className="font-display text-5xl uppercase leading-none text-white sm:text-6xl">La discipline<br /><span className="text-[#f4c660]">se partage.</span></p><p className="mt-4 max-w-xs text-sm leading-6 text-[#f4eee5]">Retrouvez l’univers de Patati et donnez une nouvelle direction à votre entraînement.</p></div>
            </div>
            <div>
              <Label>La salle de Patati</Label>
              <h2 className="font-display text-[clamp(3.8rem,7vw,6.2rem)] uppercase leading-[0.82]">Votre prochain<br /><span className="text-[#9b2d35]">point de départ.</span></h2>
              <p className="mt-8 text-base leading-7 text-[#5e5650]">À Cococodji, la salle de Marius Abadahoué, dit Patati, est le lieu pour faire le premier pas vers vos objectifs : reprendre une activité, développer votre force ou donner plus de régularité à votre pratique.</p>
              <p className="mt-4 text-sm leading-7 text-[#5e5650]">Envie d’un suivi coaching ? Une première visite permet de parler de votre niveau, de vos attentes et de vos disponibilités avec le coach, pour préparer un accompagnement adapté.</p>
              <div className="mt-8 grid gap-6 border-t border-[#171619]/15 pt-8 sm:grid-cols-2">
                {[
                  { Icon: Dumbbell, title: "Un objectif clair", copy: "Force, prise de muscle ou remise en forme : définissez ce que vous voulez construire." },
                  { Icon: ShieldCheck, title: "Un suivi à votre mesure", copy: "Échangez avec le coach pour adapter votre parcours à votre niveau et à votre rythme." },
                  { Icon: Trophy, title: "L’expérience de Patati", copy: "Découvrez l’approche de Marius et la place de la discipline dans sa pratique." },
                  { Icon: Clock3, title: "Le goût de la régularité", copy: "Faites de l’entraînement un rendez-vous dans votre semaine, avec des objectifs progressifs." },
                ].map(({ Icon, title, copy }) => <div key={title} className="flex gap-3"><Icon className="h-5 w-5 shrink-0 text-[#9b2d35]" /><div><h3 className="font-mono text-[10px] font-bold uppercase tracking-[0.12em]">{title}</h3><p className="mt-2 text-sm leading-6 text-[#6b6058]">{copy}</p></div></div>)}
              </div>
            </div>
          </div>
          <div className="mt-10 grid gap-px overflow-hidden border border-[#171619]/15 bg-[#171619]/15 md:grid-cols-3">
            <div className="bg-[#eee5d9] p-6 sm:p-8"><MapPin className="mb-4 h-5 w-5 text-[#9b2d35]" /><h3 className="font-display text-2xl uppercase">Nous trouver</h3><p className="mt-3 text-sm leading-6 text-[#5e5650]">Zone de Cococodji, Bénin</p><p className="mt-2 font-mono text-sm font-bold tracking-wider">F62W+389</p><p className="mt-1 text-xs text-[#6b6058]">Code de localisation Open Location Code</p><a href="https://www.google.com/maps/search/?api=1&query=F62W%2B389%20Cococodji%20Benin" target="_blank" rel="noopener noreferrer" className="mt-5 inline-flex items-center gap-2 border-b border-[#9b2d35] pb-1 text-sm font-semibold text-[#9b2d35]">Voir sur la carte <MoveUpRight className="h-4 w-4" /></a></div>
            <div className="bg-[#eee5d9] p-6 sm:p-8"><Clock3 className="mb-4 h-5 w-5 text-[#9b2d35]" /><h3 className="font-display text-2xl uppercase">Horaires d’ouverture</h3><p className="mt-3 text-sm font-semibold text-[#9b2d35]">À confirmer auprès de la salle</p><p className="mt-3 text-sm leading-6 text-[#5e5650]">Pour connaître les jours et heures d’ouverture exacts, renseignez-vous directement sur place ou contactez Patati via ses réseaux sociaux officiels.</p></div>
            <div className="bg-[#eee5d9] p-6 sm:p-8"><Dumbbell className="mb-4 h-5 w-5 text-[#9b2d35]" /><h3 className="font-display text-2xl uppercase">Inscription & coaching</h3><p className="mt-3 text-sm leading-6 text-[#5e5650]">Pour vous inscrire et connaître les modalités, rendez-vous sur place ou retrouvez Marius sur TikTok sous le nom <a href={socialLinks.tiktok} target="_blank" rel="noopener noreferrer" className="font-bold text-[#9b2d35] underline underline-offset-4">WFF PRO PATATI (@patati3107)</a>.</p><p className="mt-3 text-sm leading-6 text-[#5e5650]">Pour un suivi personnalisé, demandez une première visite. Le coach vous recontactera pour confirmer le créneau.</p></div>
          </div>
          <div className="mt-8 flex flex-col items-start gap-4 sm:flex-row sm:items-center sm:justify-between"><p className="max-w-lg text-sm leading-6 text-[#5e5650]">Votre objectif mérite un premier échange. Présentez votre projet au coach grâce au formulaire de visite.</p><button onClick={contact} className="flex shrink-0 items-center gap-3 bg-[#171619] px-5 py-4 font-mono text-[10px] font-bold uppercase tracking-[0.2em] text-[#f4eee5] hover:bg-[#9b2d35]">Réserver une visite coaching <ArrowRight className="h-4 w-4" /></button></div>
        </div>
      </section>
      <section id="boutique" className="scroll-mt-24 border-t border-white/10 bg-[#111113] py-24 lg:py-32">
        <div className="container">
          <div className="flex flex-col justify-between gap-8 lg:flex-row lg:items-end">
            <div><Label light>La boutique</Label><h2 className="font-display text-[clamp(3.8rem,8vw,7rem)] uppercase leading-[0.8]">Équipez<br /><span className="text-[#9b2d35]">le travail.</span></h2></div>
            <div className="max-w-sm"><p className="text-sm leading-7 text-[#b7aba1]">Nutrition, accessoires et essentiels d’entraînement : découvrez la sélection Patati et retrouvez tous les produits sur notre catalogue.</p><p className="mt-4 flex items-center gap-2 font-mono text-[10px] uppercase tracking-wider text-[#f4c660]"><Sparkles className="h-4 w-4" />Catalogue en préparation</p><a href="/catalogue" className="mt-6 inline-flex items-center gap-3 bg-[#9b2d35] px-5 py-4 font-mono text-xs font-bold uppercase tracking-wider text-white hover:bg-[#bc3943]">Voir le catalogue <ArrowRight className="h-4 w-4" /></a></div>
          </div>
          <div className="mt-12 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{products.slice(0, 4).map(product => <ProductCard key={product.name} product={product} />)}</div>
        </div>
      </section>
      <BookingForm />
      <section id="contact" className="scroll-mt-24 bg-[#9b2d35] py-20 text-[#fff8f0] lg:py-28"><div className="container grid gap-10 lg:grid-cols-[1fr_auto] lg:items-end"><div><Label light>Le prochain set</Label><h2 className="font-display text-[clamp(4rem,9vw,8rem)] uppercase leading-[0.78]">On écrit<br /><span className="text-[#f4c660]">la suite ?</span></h2><p className="mt-8 max-w-md text-sm leading-6 text-[#f6d8cf]">Visite de la salle, coaching ou sélection boutique : dites-nous où vous en êtes. Le reste se construit ensemble.</p></div><div className="flex flex-col items-start gap-3 lg:items-end"><a href={socialLinks.instagram} target="_blank" rel="noopener noreferrer" className="flex items-center gap-3 bg-[#171619] px-5 py-4 font-mono text-[10px] font-bold uppercase tracking-[0.18em] text-[#f4eee5] hover:bg-[#f4eee5] hover:text-[#171619]">Contacter Patati <ArrowRight /></a><a href={socialLinks.instagram} target="_blank" rel="noreferrer" className="flex items-center gap-3 px-2 py-3 font-mono text-[10px] font-bold uppercase tracking-[0.18em] text-[#f8ddd6] hover:text-white"><Instagram />Suivre le mouvement</a></div></div></section>
    </main>
    <Footer />
  </div>;
}
